# Generated by Django 6.0 on 2025-12-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name_kh', models.CharField(max_length=200, null=True)),
                ('mp_name_en', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_name_kh', models.CharField(max_length=200, null=True)),
                ('su_name_en', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mainprogram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='program.mainprogram')),
            ],
        ),
    ]
