# Generated by Django 6.0 on 2025-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprogram',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mainprogram',
            name='mp_name_kh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='su_name_kh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
