# Generated by Django 5.2.10 on 2026-01-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_mainprogram_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainprogram',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
