# Generated by Django 5.2.10 on 2026-01-21 01:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_teacher_image_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='teacher_image'),
        ),
    ]
